edition = "2021"
unstable_features = true

max_width = 120

enum_discrim_align_threshold = 60

error_on_unformatted = true

imports_indent = "Block"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

reorder_impl_items = true
reorder_imports = true
