[toolchain]
channel = "nightly-2023-05-04"
targets = [ "x86_64-unknown-linux-musl" ]
profile = "minimal"
components = [
    "cargo",
    "rustc",
    "rust-src", # required by IDEs
    "rustfmt",  # required for formatting
    "clippy",   # required for linting
]
